
[info 2018/06/13 13:47:46.906 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.112[41111]

[info 2018/06/13 13:47:46.914 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.112[41111]

[info 2018/06/13 13:47:46.915 IST locator <main> tid=0x1] Locator was created at Wed Jun 13 13:47:46 IST 2018

[info 2018/06/13 13:47:46.915 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/13 13:47:46.915 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/13 13:47:46.916 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/13 13:47:46.939 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/13 13:47:46.940 IST locator <main> tid=0x1] recovery file not found: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/13 13:47:46.941 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/13 13:59:13.117 IST locator <TransferQueueBundler,in-rahulkb-12850> tid=0x1d] JGRP000034: 192.168.8.112<v0>:1024: failure sending message to /192.168.8.112: java.net.SocketException: Socket is closed

[info 2018/06/13 14:00:00.655 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.112[41111]

[info 2018/06/13 14:00:00.663 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.112[41111]

[info 2018/06/13 14:00:00.664 IST locator <main> tid=0x1] Locator was created at Wed Jun 13 14:00:00 IST 2018

[info 2018/06/13 14:00:00.664 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/13 14:00:00.665 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/13 14:00:00.666 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/13 14:00:00.689 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/13 14:00:00.689 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/13 14:00:00.693 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.112(locator:13459:locator)<ec><v0>:1024|-1] members: [192.168.8.112(server1:13472)<v1>:1025{lead}, 192.168.8.112(server2:13475)<v2>:1026, 192.168.8.112(server3:13477)<v3>:1027]

[info 2018/06/13 14:00:00.694 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/13 14:01:52.372 IST locator <pool-8-thread-1> tid=0x73] Remove Proxy failed for null due to GemFire:service=Region,name=/BookMaster,type=Member,member=server2
org.apache.geode.cache.EntryDestroyedException: GemFire:service=Region,name=/BookMaster,type=Member,member=server2
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.basicGetEntry(LocalRegion.java:8695)
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.getKey(LocalRegion.java:8713)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:166)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1022)
	at org.apache.geode.management.internal.cli.functions.ShutDownFunction.lambda$disconnectInNonDaemonThread$0(ShutDownFunction.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info 2018/06/14 11:30:48.173 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:30:48.180 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:30:48.181 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 11:30:48 IST 2018

[info 2018/06/14 11:30:48.181 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 11:30:48.182 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:30:48.183 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 11:30:48.207 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 11:30:48.210 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:30:48.214 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.112(locator:14023:locator)<ec><v0>:1024|-1] members: [192.168.8.112(server1:14030)<v1>:1025{lead}, 192.168.8.112(server2:14032)<v2>:1026, 192.168.8.112(server3:14033)<v3>:1027]

[info 2018/06/14 11:30:48.215 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 11:47:34.752 IST locator <TransferQueueBundler,in-rahulkb-26635> tid=0x1d] JGRP000034: 192.168.43.163<v0>:1024: failure sending message to /192.168.43.163: java.net.SocketException: Socket is closed

[info 2018/06/14 11:48:01.987 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:48:01.995 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:48:01.996 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 11:48:01 IST 2018

[info 2018/06/14 11:48:01.996 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 11:48:01.996 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:48:01.997 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 11:48:02.020 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 11:48:02.020 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:48:02.024 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.43.163(locator:26309:locator)<ec><v0>:1024|-1] members: [192.168.43.163(server1:26333)<v1>:1025{lead}, 192.168.43.163(server2:26337)<v2>:1026, 192.168.43.163(server3:26341)<v3>:1027]

[info 2018/06/14 11:48:02.026 IST locator <main> tid=0x1] Starting distributed system

[info 2018/06/14 11:55:03.051 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:55:03.059 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.43.163[41111]

[info 2018/06/14 11:55:03.059 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 11:55:03 IST 2018

[info 2018/06/14 11:55:03.060 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 11:55:03.060 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:55:03.061 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 11:55:03.084 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 11:55:03.084 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 11:55:03.089 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.43.163(locator:27956:locator)<ec><v0>:1024|-1] members: [192.168.43.163(server1:27978)<v1>:1025{lead}, 192.168.43.163(server2:27982)<v2>:1026, 192.168.43.163(server3:27988)<v3>:1027]

[info 2018/06/14 11:55:03.090 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 12:16:37.447 IST locator <Geode Heartbeat Sender> tid=0x23] JGRP000034: 192.168.43.163<v0>:1024: failure sending message to /192.168.43.163: java.io.IOException: Can't assign requested address (sendto failed)

[warning 2018/06/14 12:16:56.634 IST locator <Geode Membership View Creator> tid=0x25] these members failed to respond to the view change: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]

[warning 2018/06/14 12:17:00.281 IST locator <Geode Membership View Creator> tid=0x25] total weight lost in this view change is 35 of 38.  Quorum has been lost!

[severe 2018/06/14 12:17:00.283 IST locator <Geode Membership View Creator> tid=0x25] Possible loss of quorum due to the loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]

[severe 2018/06/14 12:17:01.286 IST locator <Geode Membership View Creator> tid=0x25] Membership service failure: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.forceDisconnect(GMSMembershipManager.java:2531)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.forceDisconnect(GMSJoinLeave.java:1045)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.access$1500(GMSJoinLeave.java:91)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.prepareAndSendView(GMSJoinLeave.java:2490)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.createAndSendView(GMSJoinLeave.java:2466)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.run(GMSJoinLeave.java:2250)

[warning 2018/06/14 12:17:01.299 IST locator <ReconnectThread> tid=0x82] org.apache.geode.distributed.DistributedSystemDisconnectedException: Distribution manager on 192.168.43.163(locator:28425:locator)<ec><v0>:1024 started at Thu Jun 14 11:55:18 IST 2018: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027], caused by org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
org.apache.geode.management.ManagementException: org.apache.geode.distributed.DistributedSystemDisconnectedException: Distribution manager on 192.168.43.163(locator:28425:locator)<ec><v0>:1024 started at Thu Jun 14 11:55:18 IST 2018: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027], caused by org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:149)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.reconnect(InternalDistributedSystem.java:2693)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.tryReconnect(InternalDistributedSystem.java:2560)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1041)
	at org.apache.geode.distributed.internal.ClusterDistributionManager$DMListener.membershipFailure(ClusterDistributionManager.java:4033)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.uncleanShutdown(GMSMembershipManager.java:1554)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.lambda$forceDisconnect$1(GMSMembershipManager.java:2561)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.geode.distributed.DistributedSystemDisconnectedException: Distribution manager on 192.168.43.163(locator:28425:locator)<ec><v0>:1024 started at Thu Jun 14 11:55:18 IST 2018: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027], caused by org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
	at org.apache.geode.distributed.internal.ClusterDistributionManager$Stopper.generateCancelledException(ClusterDistributionManager.java:4564)
	at org.apache.geode.distributed.internal.InternalDistributedSystem$Stopper.generateCancelledException(InternalDistributedSystem.java:963)
	at org.apache.geode.internal.cache.GemFireCacheImpl$Stopper.generateCancelledException(GemFireCacheImpl.java:1557)
	at org.apache.geode.CancelCriterion.checkCancelInProgress(CancelCriterion.java:83)
	at org.apache.geode.internal.cache.LocalRegion.checkRegionDestroyed(LocalRegion.java:7381)
	at org.apache.geode.internal.cache.LocalRegion.checkReadiness(LocalRegion.java:2723)
	at org.apache.geode.internal.cache.LocalRegion.entrySet(LocalRegion.java:1863)
	at org.apache.geode.internal.cache.LocalRegion.entrySet(LocalRegion.java:8906)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:154)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	... 15 more
Caused by: org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v2>:1026, 192.168.43.163(server3:28459)<v3>:1027]
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.forceDisconnect(GMSMembershipManager.java:2531)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.forceDisconnect(GMSJoinLeave.java:1045)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.access$1500(GMSJoinLeave.java:91)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.prepareAndSendView(GMSJoinLeave.java:2490)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.createAndSendView(GMSJoinLeave.java:2466)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.run(GMSJoinLeave.java:2250)

[warning 2018/06/14 12:29:26.530 IST locator <Geode Failure Detection thread 1> tid=0xd2] JGRP000034: 192.168.43.163<v0>:1024: failure sending message to /192.168.43.163: java.io.IOException: Can't assign requested address (sendto failed)

[warning 2018/06/14 12:29:54.863 IST locator <Geode Membership View Creator> tid=0x96] these members failed to respond to the view change: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v1>:1026, 192.168.43.163(server3:28459)<v1>:1027]

[warning 2018/06/14 12:30:07.308 IST locator <Geode Membership View Creator> tid=0x96] total weight lost in this view change is 35 of 38.  Quorum has been lost!

[severe 2018/06/14 12:30:07.309 IST locator <Geode Membership View Creator> tid=0x96] Possible loss of quorum due to the loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v1>:1026, 192.168.43.163(server3:28459)<v1>:1027]

[severe 2018/06/14 12:30:08.311 IST locator <Geode Membership View Creator> tid=0x96] Membership service failure: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v1>:1026, 192.168.43.163(server3:28459)<v1>:1027]
org.apache.geode.ForcedDisconnectException: Exiting due to possible network partition event due to loss of 3 cache processes: [192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server2:28449)<v1>:1026, 192.168.43.163(server3:28459)<v1>:1027]
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.forceDisconnect(GMSMembershipManager.java:2531)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.forceDisconnect(GMSJoinLeave.java:1045)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.access$1500(GMSJoinLeave.java:91)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.prepareAndSendView(GMSJoinLeave.java:2490)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.createAndSendView(GMSJoinLeave.java:2466)
	at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave$ViewCreator.run(GMSJoinLeave.java:2250)

[severe 2018/06/14 12:31:09.374 IST locator <ReconnectThread> tid=0xd8] Unexpected exception while booting membership services
org.apache.geode.SystemConnectException: Unable to find a free port in the membership-port-range
	at org.apache.geode.internal.net.SocketCreator.createServerSocketUsingPortRange(SocketCreator.java:817)
	at org.apache.geode.internal.net.SocketCreator.createServerSocketUsingPortRange(SocketCreator.java:776)
	at org.apache.geode.internal.tcp.TCPConduit.createServerSocket(TCPConduit.java:455)
	at org.apache.geode.internal.tcp.TCPConduit.startAcceptor(TCPConduit.java:413)
	at org.apache.geode.internal.tcp.TCPConduit.<init>(TCPConduit.java:295)
	at org.apache.geode.distributed.internal.direct.DirectChannel.<init>(DirectChannel.java:152)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.start(GMSMembershipManager.java:732)
	at org.apache.geode.distributed.internal.membership.gms.Services.start(Services.java:163)
	at org.apache.geode.distributed.internal.membership.gms.GMSMemberFactory.newMembershipManager(GMSMemberFactory.java:106)
	at org.apache.geode.distributed.internal.membership.MemberFactory.newMembershipManager(MemberFactory.java:90)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1027)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1061)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.create(ClusterDistributionManager.java:554)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.initialize(InternalDistributedSystem.java:763)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:355)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:341)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:335)
	at org.apache.geode.distributed.DistributedSystem.connect(DistributedSystem.java:211)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.reconnect(InternalDistributedSystem.java:2736)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.tryReconnect(InternalDistributedSystem.java:2560)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1041)
	at org.apache.geode.distributed.internal.ClusterDistributionManager$DMListener.membershipFailure(ClusterDistributionManager.java:4033)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.uncleanShutdown(GMSMembershipManager.java:1554)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.lambda$forceDisconnect$1(GMSMembershipManager.java:2561)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 12:31:09.376 IST locator <ReconnectThread> tid=0xd8] Caught SystemConnectException in reconnect
org.apache.geode.SystemConnectException: Unable to find a free port in the membership-port-range
	at org.apache.geode.internal.net.SocketCreator.createServerSocketUsingPortRange(SocketCreator.java:817)
	at org.apache.geode.internal.net.SocketCreator.createServerSocketUsingPortRange(SocketCreator.java:776)
	at org.apache.geode.internal.tcp.TCPConduit.createServerSocket(TCPConduit.java:455)
	at org.apache.geode.internal.tcp.TCPConduit.startAcceptor(TCPConduit.java:413)
	at org.apache.geode.internal.tcp.TCPConduit.<init>(TCPConduit.java:295)
	at org.apache.geode.distributed.internal.direct.DirectChannel.<init>(DirectChannel.java:152)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.start(GMSMembershipManager.java:732)
	at org.apache.geode.distributed.internal.membership.gms.Services.start(Services.java:163)
	at org.apache.geode.distributed.internal.membership.gms.GMSMemberFactory.newMembershipManager(GMSMemberFactory.java:106)
	at org.apache.geode.distributed.internal.membership.MemberFactory.newMembershipManager(MemberFactory.java:90)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1027)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1061)
	at org.apache.geode.distributed.internal.ClusterDistributionManager.create(ClusterDistributionManager.java:554)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.initialize(InternalDistributedSystem.java:763)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:355)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:341)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:335)
	at org.apache.geode.distributed.DistributedSystem.connect(DistributedSystem.java:211)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.reconnect(InternalDistributedSystem.java:2736)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.tryReconnect(InternalDistributedSystem.java:2560)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1041)
	at org.apache.geode.distributed.internal.ClusterDistributionManager$DMListener.membershipFailure(ClusterDistributionManager.java:4033)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.uncleanShutdown(GMSMembershipManager.java:1554)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.lambda$forceDisconnect$1(GMSMembershipManager.java:2561)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 12:32:09.379 IST locator <ReconnectThread> tid=0xd8] Exception occurred while trying to connect the system during reconnect
org.apache.geode.GemFireIOException: Failed reading  file:/Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/gemfire-server.properties
	at org.apache.geode.distributed.internal.DistributionConfigImpl.loadPropertiesFromURL(DistributionConfigImpl.java:1592)
	at org.apache.geode.distributed.internal.DistributionConfigImpl.loadPropertiesFromURL(DistributionConfigImpl.java:1579)
	at org.apache.geode.distributed.internal.DistributionConfigImpl.<init>(DistributionConfigImpl.java:916)
	at org.apache.geode.distributed.internal.DistributionConfigImpl.<init>(DistributionConfigImpl.java:879)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.<init>(InternalDistributedSystem.java:530)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:354)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:341)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:335)
	at org.apache.geode.distributed.DistributedSystem.connect(DistributedSystem.java:211)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.reconnect(InternalDistributedSystem.java:2736)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.tryReconnect(InternalDistributedSystem.java:2560)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1041)
	at org.apache.geode.distributed.internal.ClusterDistributionManager$DMListener.membershipFailure(ClusterDistributionManager.java:4033)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.uncleanShutdown(GMSMembershipManager.java:1554)
	at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.lambda$forceDisconnect$1(GMSMembershipManager.java:2561)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/gemfire-server.properties (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at org.apache.geode.distributed.internal.DistributionConfigImpl.loadPropertiesFromURL(DistributionConfigImpl.java:1589)
	... 15 more

[info 2018/06/14 12:38:05.320 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 12:38:05.327 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 12:38:05.328 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 12:38:05 IST 2018

[info 2018/06/14 12:38:05.328 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 12:38:05.329 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 12:38:05.329 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 12:38:05.354 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 12:38:05.354 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 12:38:05.357 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.43.163(locator:28425:locator)<ec><v0>:1024|-1] members: [192.168.43.163(server2:28449)<v1>:1026{lead}, 192.168.43.163(server1:28445)<v1>:1025, 192.168.43.163(server3:28459)<v1>:1027]

[info 2018/06/14 12:38:05.358 IST locator <main> tid=0x1] Starting distributed system

[info 2018/06/14 13:41:11.004 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:41:11.012 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:41:11.013 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 13:41:11 IST 2018

[info 2018/06/14 13:41:11.013 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 13:41:11.014 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:41:11.015 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 13:41:11.039 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 13:41:11.039 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:41:11.042 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:29547:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:29560)<v1>:1025{lead}, 192.168.8.100(server2:29565)<v2>:1026, 192.168.8.100(server3:29567)<v3>:1027]

[info 2018/06/14 13:41:11.044 IST locator <main> tid=0x1] Starting distributed system

[info 2018/06/14 13:45:00.462 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:45:00.471 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:45:00.472 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 13:45:00 IST 2018

[info 2018/06/14 13:45:00.472 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 13:45:00.473 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:45:00.473 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 13:45:00.504 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 13:45:00.504 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:45:00.507 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:30047:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:30060)<v1>:1025{lead}, 192.168.8.100(server2:30062)<v2>:1026, 192.168.8.100(server3:30063)<v3>:1027]

[info 2018/06/14 13:45:00.510 IST locator <main> tid=0x1] Starting distributed system

[info 2018/06/14 13:46:21.092 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:46:21.100 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 13:46:21.101 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 13:46:21 IST 2018

[info 2018/06/14 13:46:21.101 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 13:46:21.101 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:46:21.102 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 13:46:21.125 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 13:46:21.125 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 13:46:21.128 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:30270:locator)<ec><v0>:1024|-1] members: []  shutdown: [192.168.8.100(server1:30276)<v1>:1025]

[info 2018/06/14 13:46:21.129 IST locator <main> tid=0x1] Starting distributed system

[info 2018/06/14 14:09:56.390 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:09:56.398 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:09:56.398 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:09:56 IST 2018

[info 2018/06/14 14:09:56.399 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:09:56.399 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:09:56.400 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:09:56.423 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:09:56.424 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:09:56.426 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:30525:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:30527)<v1>:1025{lead}, 192.168.8.100(server2:30528)<v2>:1026, 192.168.8.100(server3:30530)<v3>:1027]

[info 2018/06/14 14:09:56.427 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:22:39.226 IST locator <TransferQueueBundler,in-rahulkb-22157> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:22:45.880 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:22:45.887 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:22:45.888 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:22:45 IST 2018

[info 2018/06/14 14:22:45.888 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:22:45.889 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:22:45.890 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:22:45.913 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:22:45.913 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:22:45.916 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:30831:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:30839)<v1>:1025{lead}, 192.168.8.100(server2:30840)<v2>:1026, 192.168.8.100(server3:30841)<v3>:1027]

[info 2018/06/14 14:22:45.917 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:24:43.900 IST locator <pool-8-thread-1> tid=0x74] Remove Proxy failed for null due to GemFire:service=Region,name=/Users,type=Member,member=server1
org.apache.geode.cache.EntryDestroyedException: GemFire:service=Region,name=/Users,type=Member,member=server1
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.basicGetEntry(LocalRegion.java:8695)
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.getKey(LocalRegion.java:8713)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:166)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1022)
	at org.apache.geode.management.internal.cli.functions.ShutDownFunction.lambda$disconnectInNonDaemonThread$0(ShutDownFunction.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 14:24:43.903 IST locator <pool-8-thread-1> tid=0x74] Remove Proxy failed for null due to GemFire:service=Region,name=/BookMaster,type=Member,member=server1
org.apache.geode.cache.EntryDestroyedException: GemFire:service=Region,name=/BookMaster,type=Member,member=server1
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.basicGetEntry(LocalRegion.java:8695)
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.getKey(LocalRegion.java:8713)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:166)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1022)
	at org.apache.geode.management.internal.cli.functions.ShutDownFunction.lambda$disconnectInNonDaemonThread$0(ShutDownFunction.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 14:24:45.189 IST locator <TransferQueueBundler,in-rahulkb-40588> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:24:49.066 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:24:49.074 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:24:49.075 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:24:49 IST 2018

[info 2018/06/14 14:24:49.075 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:24:49.076 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:24:49.076 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:24:49.100 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:24:49.100 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:24:49.103 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:31122:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:31125)<v1>:1025{lead}, 192.168.8.100(server2:31127)<v2>:1026, 192.168.8.100(server3:31128)<v3>:1027]

[info 2018/06/14 14:24:49.104 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:27:28.789 IST locator <pool-8-thread-1> tid=0x74] Remove Proxy failed for null due to GemFire:service=CacheServer,port=52762,type=Member,member=server2
org.apache.geode.cache.EntryDestroyedException: GemFire:service=CacheServer,port=52762,type=Member,member=server2
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.basicGetEntry(LocalRegion.java:8695)
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.getKey(LocalRegion.java:8713)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:166)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1022)
	at org.apache.geode.management.internal.cli.functions.ShutDownFunction.lambda$disconnectInNonDaemonThread$0(ShutDownFunction.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 14:27:30.057 IST locator <TransferQueueBundler,in-rahulkb-23919> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:27:34.974 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:27:34.982 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:27:34.983 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:27:34 IST 2018

[info 2018/06/14 14:27:34.983 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:27:34.983 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:27:34.984 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:27:35.007 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:27:35.008 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:27:35.011 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:31312:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:31316)<v1>:1025{lead}, 192.168.8.100(server2:31317)<v2>:1026, 192.168.8.100(server3:31319)<v3>:1027]

[info 2018/06/14 14:27:35.012 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:29:24.232 IST locator <pool-8-thread-1> tid=0x74] Remove Proxy failed for null due to GemFire:service=Region,name=/BookMaster,type=Member,member=server2
org.apache.geode.cache.EntryDestroyedException: GemFire:service=Region,name=/BookMaster,type=Member,member=server2
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.basicGetEntry(LocalRegion.java:8695)
	at org.apache.geode.internal.cache.LocalRegion$NonTXEntry.getKey(LocalRegion.java:8713)
	at org.apache.geode.management.internal.MBeanProxyFactory.removeAllProxies(MBeanProxyFactory.java:166)
	at org.apache.geode.management.internal.FederatingManager.removeMemberArtifacts(FederatingManager.java:223)
	at org.apache.geode.management.internal.FederatingManager.stopManagingActivity(FederatingManager.java:145)
	at org.apache.geode.management.internal.FederatingManager.stopManager(FederatingManager.java:133)
	at org.apache.geode.management.internal.SystemManagementService.close(SystemManagementService.java:235)
	at org.apache.geode.management.internal.beans.ManagementAdapter.handleCacheRemoval(ManagementAdapter.java:744)
	at org.apache.geode.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:110)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2202)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:591)
	at org.apache.geode.internal.cache.GemFireCacheImpl.close(GemFireCacheImpl.java:2148)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1372)
	at org.apache.geode.distributed.internal.InternalDistributedSystem.disconnect(InternalDistributedSystem.java:1022)
	at org.apache.geode.management.internal.cli.functions.ShutDownFunction.lambda$disconnectInNonDaemonThread$0(ShutDownFunction.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning 2018/06/14 14:29:25.510 IST locator <TransferQueueBundler,in-rahulkb-3330> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:29:28.325 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:29:28.333 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:29:28.334 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:29:28 IST 2018

[info 2018/06/14 14:29:28.334 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:29:28.335 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:29:28.335 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:29:28.358 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:29:28.359 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:29:28.361 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:31774:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:31784)<v1>:1025{lead}, 192.168.8.100(server2:31786)<v2>:1026, 192.168.8.100(server3:31787)<v3>:1027]

[info 2018/06/14 14:29:28.362 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:36:37.942 IST locator <TransferQueueBundler,in-rahulkb-41341> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:36:42.393 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:36:42.401 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:36:42.401 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:36:42 IST 2018

[info 2018/06/14 14:36:42.402 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:36:42.402 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:36:42.403 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:36:42.426 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:36:42.427 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:36:42.430 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:31971:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:31974)<v1>:1025{lead}, 192.168.8.100(server2:31976)<v2>:1026, 192.168.8.100(server3:31978)<v3>:1027]

[info 2018/06/14 14:36:42.431 IST locator <main> tid=0x1] Starting distributed system

[warning 2018/06/14 14:44:58.245 IST locator <TransferQueueBundler,in-rahulkb-7612> tid=0x1d] JGRP000034: 192.168.8.100<v0>:1024: failure sending message to /192.168.8.100: java.net.SocketException: Socket is closed

[info 2018/06/14 14:45:17.224 IST locator <main> tid=0x1] Starting peer location for Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:45:17.231 IST locator <main> tid=0x1] Starting Distribution Locator on 192.168.8.100[41111]

[info 2018/06/14 14:45:17.232 IST locator <main> tid=0x1] Locator was created at Thu Jun 14 14:45:17 IST 2018

[info 2018/06/14 14:45:17.232 IST locator <main> tid=0x1] Listening on port 41111 bound on address 0.0.0.0/0.0.0.0

[info 2018/06/14 14:45:17.233 IST locator <main> tid=0x1] GemFire peer location service starting.  Other locators: localhost[41111]  Locators preferred as coordinators: true  Network partition detection enabled: true  View persistence file: /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:45:17.233 IST locator <main> tid=0x1] Peer locator attempting to recover from localhost/127.0.0.1:41111

[info 2018/06/14 14:45:17.257 IST locator <main> tid=0x1] Peer locator was unable to recover state from this locator

[info 2018/06/14 14:45:17.257 IST locator <main> tid=0x1] Peer locator recovering from /Users/rahul/Development/gemfire_prac/scala-gemfire-prac/server-bootstrap/locator/locator41111view.dat

[info 2018/06/14 14:45:17.260 IST locator <main> tid=0x1] Peer locator recovered membership is View[192.168.8.100(locator:32208:locator)<ec><v0>:1024|-1] members: [192.168.8.100(server1:32212)<v1>:1025{lead}, 192.168.8.100(server2:32213)<v2>:1026, 192.168.8.100(server3:32215)<v3>:1027]

[info 2018/06/14 14:45:17.261 IST locator <main> tid=0x1] Starting distributed system
